### ISSUE TITLE
TypeError: pluginOptions.modifyLessRule is not a function

### ISSUE THREAD

**Issue by leotaozeng** [w3ctech-editorial-department/craco-antd-mobile#1]
When I try to run the app, it shows `UnhandledPromiseRejectionWarning: TypeError: pluginOptions.modifyLessRule is not a function`

![image](https://user-images.githubusercontent.com/12603244/132295334-6213374a-8004-4fd7-a436-81a36b4ec4ae.png)

![image](https://user-images.githubusercontent.com/12603244/132295345-ed57f9c6-3fa1-41c3-bd04-d754de773e1d.png)

**Comment by liuliangsir** [comment]
@Zeng95 thanks for feedback, I'll fix the issue above.

**Comment by liuliangsir** [comment]
@Zeng95 you can now try installing [latest version](https://www.npmjs.com/package/@w3ctech-editorial-department/craco-antd-mobile/v/1.0.2) of w3ctech-editorial-department/craco-antd-mobile.
